import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { DataProvider } from "../providers/data";
import { OptionsProvider } from "../providers/options";
import { SelectedProvider } from "../providers/selected";

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
          rel="stylesheet"
        ></link>
      </head>{" "}
      <body className={inter.className}>
        <DataProvider>
          <OptionsProvider>
            <SelectedProvider>{children}</SelectedProvider>
          </OptionsProvider>
        </DataProvider>
      </body>
    </html>
  );
}
